name: example
description: Example Dart script demonstrating sqflite_orm usage
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  sqflite_orm:
    path: ../
  sqflite_common: ^2.5.6

