name: sqflite_orm
description: Cross-platform SQLite ORM for Flutter and Dart with automatic migrations, relationships, query builder, and web UI.
version: 0.1.10
homepage: https://github.com/sbrsubuvga/sqflite-orm
repository: https://github.com/sbrsubuvga/sqflite-orm
issue_tracker: https://github.com/sbrsubuvga/sqflite-orm/issues
license: MIT

environment:
  sdk: '>=3.0.0 <4.0.0'

platforms:
  android:
  ios:
  windows:
  macos:
  linux:

dependencies:
  sqflite: ^2.4.2
  sqflite_common: ^2.5.6
  sqflite_common_ffi: ^2.4.0+2
  sqflite_dev: ^1.0.5
  meta: ^1.17.0
  collection: ^1.19.1

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  source_gen: ^4.1.1
  test: ^1.29.0

